### ISSUE TITLE
The environment.yml should be carefully checked

### ISSUE THREAD

**Issue by hongxin001** [Jingkang50/OpenOOD#106]
Hi,

Thanks for your great work. I'd like to run the script but I found the [environment.yml](https://github.com/Jingkang50/OpenOOD/blob/main/environment.yml) cannot be directly installed in many GPU machines. The problem might be caused by the version of Cython.

Best Regards,
Hongxin

**Comment by Jingkang50** [comment]
Hi Hongxin,

I checked the environment.yml and it works on both local machine and multi-gpu servers.
Could you elaborate the problem you get?

Thanks!

**Comment by Jingkang50** [comment]
Hi Hongxin,
I notice that you are also from NTU. Are you on campus recently? 
We can meet in person on this if you like.

**Comment by sabyasachis** [comment]
I received the same error. Posting error screenshot for your reference:

<img width="1195" alt="Screen Shot 2022-07-07 at 9 34 31 AM" src="https://user-images.githubusercontent.com/21968975/177786710-e638cd0d-4374-420d-be39-747b81153de3.png">
