### ISSUE TITLE
Missing FSOOD Dataset?

### ISSUE THREAD

**Issue by JaeLee18** [Jingkang50/OpenOOD#114]
Hello,
Thank you for maintaining this OOD repo!

I tried to run `FSOOD` but I got this FileNotFoundError
`FileNotFoundError: [Errno 2] No such file or directory: './data/imglist/digits/val_notmnist.txt'`
Could you check this issue or tell me how to handle this? I put all the data from this repo so I was able to run other ood tests.

**Comment by zjysteven** [comment]
Hi @JaeLee18, this is a long shot but OpenOOD now supports full-spectrum detection (for ImageNet-200 and ImageNet-1K) in its v1.5 release. See below script as an example (https://github.com/Jingkang50/OpenOOD/blob/main/scripts/ood/react/imagenet_test_ood_react.sh#L42C1-L47).
```bash
# full-spectrum ood
python scripts/eval_ood_imagenet.py \
   --tvs-pretrained \
   --arch resnet50 \
   --postprocessor react \
   --save-score --save-csv --fsood
```
Let us know if you have further questions.
