### ISSUE TITLE
Traning on multiple GPU

### ISSUE THREAD

**Issue by Lature-Yang** [Jingkang50/OpenOOD#115]
Hi，thanks for your excellent work. When I tran the network on my gpus, I foud that it can only train on a single GPU. Do you know how to train on multi machines?

**Comment by Jingkang50** [comment]
Sorry we are busy on some other stuff. Will fix soon

**Comment by Lature-Yang** [comment]
> Sorry we are busy on some other stuff. Will fix soon

Thanks for your attention reply, I have figured it out by setting num_gpus in  train.sh  and adding the 'net=net.module' 
 at line 255 in openood/networks/utils.py .
