### ISSUE TITLE
Where are the labels for MOS training?

### ISSUE THREAD

**Issue by yang-william** [Jingkang50/OpenOOD#120]
Thank you for the great work. I'm trying to train a model using MOS but the template requires the following path`imglist_pth: ./data/benchmark_imglist/cifar10/train_cifar10_mos.txt`. The following file doesn't seem to be present in the SharePoint. Is there a way to resolve this? Thanks for the help!

**Comment by Jingkang50** [comment]
@OmegaDING @Prophet-C Please help with this issue.

**Comment by OmegaDING** [comment]
[train_cifar10_mos.txt](https://github.com/Jingkang50/OpenOOD/files/10024987/train_cifar10_mos.txt)
[test_cifar10_mos.txt](https://github.com/Jingkang50/OpenOOD/files/10024991/test_cifar10_mos.txt)
you can try with this, 
In simple terms, it puts a json string in the label's place that contains group_label and class_label. Corresponding to its group tag and class tag, respectively
