### ISSUE TITLE
Problem about scripts/ood/knn/imagenet_test_ood_knn.sh

### ISSUE THREAD

**Issue by CS123n** [Jingkang50/OpenOOD#121]
ERROR:root:[Errno 2] No such file or directory: './data/images_largescale/imagenet_1k/train/n09421951/n09421951_14600.JPEG'
Hi, I only find the valid dataset of imagenet in Onedrive. What should I do?

**Comment by Jingkang50** [comment]
You might need to download imagenet 1k training set on your own.
The data is too big so we do not support here.

**Comment by Jingkang50** [comment]
Did you made it to get imagenet_1k training?
