### ISSUE TITLE
How to start executing this project via command line

### ISSUE THREAD

**Issue by yangengineering** [Jingkang50/OpenOOD#127]
How to start executing this project via command line, can you give an example

**Comment by Jingkang50** [comment]
Did you follow the instruction of https://github.com/Jingkang50/OpenOOD#get-started ?

**Comment by yangengineering** [comment]
HI，
I noticed that ,but I also have a question about the Dataset Preparation. Do these datasets have to be downloaded manually and set according to the format? Is there any download related content in the code?
thanks

**Comment by Jingkang50** [comment]
https://github.com/Jingkang50/OpenOOD#:~:text=Datasets%20and%20pretrained%20models%20are%20provided%20here.%20Please%20unzip%20the%20files%20if%20necessary.%20We%20also%20provide%20an%20automatic%20data%20download%20script%20here.

**Comment by yangengineering** [comment]
thanks，sir
but when I use that project to download the data, the wrong is that "由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败"
