### ISSUE TITLE
About the problem that test_ood can only be tested correctly once

### ISSUE THREAD

**Issue by yangengineering** [Jingkang50/OpenOOD#134]
Hello, first of all thank you very much for providing such an excellent code base.
But I personally encountered a problem in the process of running:
I used the per-model you provided, and tested it under the msp method, and the result of the first test was normal. But I did the same second test without any changes and this time I found the FPR above 90 and the AUROC very low. I also found this problem after changing the graphics card: the first test was fine, the second test was obviously wrong.
So I would like to ask whether some of the cuda operators written by yourself are used in your code base so that the code of test_ood can only be run once.
thank you very much.

**Comment by Jingkang50** [comment]
Is the problem still there? If so, we can have a quick zoom meeting to discuss on your problem.
