### ISSUE TITLE
Issues with ViT

### ISSUE THREAD

**Issue by charlesGE** [Jingkang50/OpenOOD#144]
Hello,

There are several serious issues with the use of ViT.
- Perhaps one of the easiest to fix is that currently, with the config file provided as an example, images are center-cropped to 384 (to fit the input size of ViT). However, the pre_size is left to default e.g. 256 for ImageNet or even less for other datasets.
This means that the preprocessor behavior will be to resize to 256, then pad to 384, leading to bad performances (~70% accuracy instead of ~84% expected). The config file should include : config.dataset.pre_size = 384 (or 400 for some slight center crop).

- But a more serious issue is that the current implementation cannot possibly work because the current wrapper for ViT, ImageClassifierWithReturnFeature, does not handle the 'return_loss' kwargs of the parent class (ImageClassifier from mmcls). By default, 'return_loss' is set to True, which returns the loss, and must be set to False to get the output. The wrapper must either set return_loss to False, or directly compute the output using extract_feat() and head.layers(). Additionally, the wrapper does not yet support return_feature_list, which is required for certain methods (e.g. mahalanobis). This can be done by setting `model.backbone.out_indices = range(len(self.backbone.layers))`

**Comment by zjysteven** [comment]
With recent updates we are able to evaluate ViT (specifically ViT-B-16) on ImageNet (see this [tutorial](../example_eval_imagenet.ipynb)). Basically this time we wrap around the torchvision implementation of ViTs, which should solve the issues you mentioned above. Let us know if there are any other problems.

**Comment by MaxTorop** [comment]
First off, thank you so much for this wonderful benchmark. It has really streamlined my research! Unfortunately, the tutorial link you posted in your previous comment gives a 404 page not found error. Could you please repost the tutorial ?

**Comment by zjysteven** [comment]
Hi @MaxTorop thank you for your kind words. The tutorial is [here](https://colab.research.google.com/drive/1tvTpCM1_ju82Yygu40fy7Lc0L1YrlkQF?usp=sharing). We switched to using CIFAR-10 for the tutorial (otherwise the imagenet data need to be downloaded which is too cumbersome for Colab). However evaluating on ImageNet is pretty much the same. Please also see example evaluation script [here](https://github.com/Jingkang50/OpenOOD/blob/main/scripts/eval_ood_imagenet.py).
