### ISSUE TITLE
To many blank link in readme

### ISSUE THREAD

**Issue by Tom-Teamo** [Jingkang50/OpenOOD#148]
There are too many links which are blank, so we can see Page Not Found after clicking them. such as links in ``OOD Benchmark Table``. Hope you can fix it.

**Comment by Jingkang50** [comment]
Thank you for pointing it out. Do you mean the "Supported Benchmarks (10)" section?

**Comment by Tom-Teamo** [comment]
Not really, it is in "Get Started" section, also in  the "Supported Benchmarks (10)" section, OOD(5) part has the same problem.

**Comment by zjysteven** [comment]
We've updated the readme accompanying our `v1.5` release. Some "links" are put there kind of only for visual highlighting effects. This is not ideal, but please let us know if you find any important links missing.

**Comment by zjysteven** [comment]
Closing now. Feel free to reopen if you have further questions.
