### ISSUE TITLE
Regarding the problem that the accuracy has not changed 

### ISSUE THREAD

**Issue by yangengineering** [Jingkang50/OpenOOD#149]
Hello, first of all, thank you very much for the code you summarized, but I found a problem in the process of using the code. This question is about the fact that when I tested the nearood and farood data of ood in various ways, I found that the accuracy values ​​of the data sets of ood did not change under each method. For example, I use "sh scripts/ood/msp/mnist_test_ood_msp.sh" test but found that the accuracy of each data set is 98.88.
I'm very strange about this, so really looking forward to your reply。

**Comment by yangengineering** [comment]
![image](https://user-images.githubusercontent.com/117337127/225562699-9e256ba3-6c0c-4ccd-8ecb-838b21d48dae.png)

**Comment by 2454511550Lin** [comment]
I think this ACC 98.88% refers to the in-distribution accuracy of the model. In this case, it is the accuracy of Lenet on the MNIST testing dataset?

**Comment by zjysteven** [comment]
Exactly. The `ACC` is ID accuracy, so it doesn't change across different OOD datasets.
