### ISSUE TITLE
Where to download the ckpt for mnist with an accuracy of 98.50%?

### ISSUE THREAD

**Issue by Correr-Zhou** [Jingkang50/OpenOOD#153]
Hi, there.
Many thanks for your excellent open-source repo.
I found out that the pretrained mnist models your provided is with an accuracy of 99.60% (which is different from the data you report).
So where to download the ckpt for mnist with an accuracy of 98.50%?

**Comment by zjysteven** [comment]
Sorry for the late reply. Unfortunately, we have developed a newer, larger version (v1.5) where we have refrained from evaluating on MNIST. That said, I don't exactly see why the model having a higher accuracy is a problem here. Would you clarify a little bit?

Closing for now, but feel free to reopen if there are any other issues.
