### ISSUE TITLE
Trainer for SimCLR network?

### ISSUE THREAD

**Issue by 2454511550Lin** [Jingkang50/OpenOOD#155]
Hi, I tried to train Resnet-50 with SimCLR loss on Cifar10 from scratch. The scrip is as follows:
`python main.py 
--config configs/datasets/cifar10/cifar10.yml 
configs/preprocessors/base_preprocessor.yml 
configs/networks/simclr.yml 
configs/pipelines/train/?.yml`
I am wondering which trainer from `openood/trainers/` should I choose?

Besides, I am wondering if there are pre-trained SimCLR ResNet models for Cifar-10/100 available. Thank you so much.

**Comment by zjysteven** [comment]
I don't think we provide the exact SimCLR trainer. However, CIDER and NPOS uses SimCLR-like contrastive training if I remember correctly.
