### ISSUE TITLE
Checkpoint for ensemble-based methods

### ISSUE THREAD

**Issue by flymin** [Jingkang50/OpenOOD#159]
Hi,

The paper has results for ensemble-based methods like MCDropout and DeepEnsemble. These methods require re-training the classifier. However, the released checkpoints do not contain these checkpoints. Could you please provide checkpoints for ensemble-based methods?

By the way, does `scripts/uncertainty/ensemble` indicate DeepEnsemble? If so, how to train the model used for testing good on cifar10?

Thank you.

**Comment by zjysteven** [comment]
I don't think we provide (or plan to provide) checkpoints for ensemble-based method. They should be pretty easy and fast to train especially on small datasets like CIFAR.

Correct me if I'm wrong, but I think `DeepEnsemble` just ensembles multiple independently trained models? Therefore you can just use the single-model training script to train several models and ensemble them for testing.
