### ISSUE TITLE
Do not use the "environment.yml" to create the envs !

### ISSUE THREAD

**Issue by yushaodong** [Jingkang50/OpenOOD#160]
Thanks for developing and sharing the OpenOOD. But the environment is to old for the source code. Such as torchvision 0.9.1, there is no torchvision.models.vision_transformer in this version. There are some other similar problems.

**Comment by zjysteven** [comment]
OpenOOD now supports `pip install git+ https://github.com/Jingkang50/OpenOOD/`. Please have a try and let us know if there are any issues. We are about to make a new v1.5 release with updated readme in 1-2 weeks. Stay tuned!

**Comment by yushaodong** [comment]
> OpenOOD now supports `pip install git+https://github.com/Jingkang50/OpenOOD/`. Please have a try and let us know if there are any issues. We are about to make a new v1.5 release with updated readme in 1-2 weeks. Stay tuned!

Thank you for  your replay! I'm looking forward to the new version. The OpenOOD is very helpful for my work. Thanks again!

**Comment by zjysteven** [comment]
@yushaodong We've updated the readme. Also there is a changelog in the Wiki that documents the new updates for OpenOOD v1.5 release. Closing now, but feel free to reopen if you have any other questions.
