### ISSUE TITLE
Add GEN OOD detection

### ISSUE THREAD

**Issue by coding-famer** [Jingkang50/OpenOOD#172]
I create a pull request with the implementation of [GEN](https://openaccess.thecvf.com/content/CVPR2023/papers/Liu_GEN_Pushing_the_Limits_of_Softmax-Based_Out-of-Distribution_Detection_CVPR_2023_paper.pdf). And here I want to report its results for further discussion and add it to the leaderboard.

+ `Training`: CrossEntropy
+ `Postprocessor`: GEN
+ `Near-OOD AUROC`: See tables below
+ `Far-OOD AUROC`: See tables below
+ `ID Accuracy`: The accuracy of original model.
+ `Outlier Data`: No
+ `Model Arch`: See tables below

## CIFAR10
||FPR@95       |AUROC       |AUPR_IN     |AUPR_OUT    |CCR_4      |CCR_3       |CCR_2        |CCR_1       |ACC         |
|---------|-------------|------------|------------|------------|-----------|------------|-------------|------------|------------|
|cifar100 |54.86 ± 2.51 |87.21 ± 0.36|84.99 ± 0.85|86.62 ± 0.21|0.05 ± 0.04|1.38 ± 0.40 |9.24 ± 1.74  |65.89 ± 2.20|95.06 ± 0.30|
|tin      |49.96 ± 2.34 |89.20 ± 0.25|88.82 ± 0.72|87.22 ± 0.13|0.24 ± 0.22|1.42 ± 0.72 |11.92 ± 2.84 |73.66 ± 1.28|95.06 ± 0.30|
|nearood  |52.41 ± 2.42 |88.20 ± 0.30|86.90 ± 0.79|86.92 ± 0.16|0.14 ± 0.12|1.40 ± 0.54 |10.58 ± 2.22 |69.77 ± 1.74|95.06 ± 0.30|
|mnist    |35.31 ± 11.14|93.83 ± 2.14|76.04 ± 9.19|98.95 ± 0.39|6.59 ± 5.23|16.04 ± 9.76|46.74 ± 17.40|84.39 ± 3.46|95.06 ± 0.30|
|svhn     |45.42 ± 7.01 |91.97 ± 0.66|82.41 ± 1.66|96.37 ± 0.41|0.94 ± 0.36|5.09 ± 1.52 |30.26 ± 5.93 |81.40 ± 0.72|95.06 ± 0.30|
|texture  |48.08 ± 3.34 |90.14 ± 0.76|92.02 ± 1.18|84.71 ± 0.89|0.16 ± 0.20|0.71 ± 0.79 |11.96 ± 6.70 |76.57 ± 2.46|95.06 ± 0.30|
|places365|48.66 ± 3.98 |89.46 ± 0.65|67.54 ± 2.62|96.67 ± 0.22|0.41 ± 0.23|2.03 ± 0.89 |13.27 ± 3.89 |73.95 ± 1.06|95.06 ± 0.30|
|farood   |44.37 ± 5.86 |91.35 ± 0.69|79.50 ± 2.98|94.18 ± 0.24|2.03 ± 1.40|5.97 ± 2.52 |25.56 ± 4.47 |79.08 ± 0.68|95.06 ± 0.30|

## CIFAR100
||FPR@95      |AUROC       |AUPR_IN     |AUPR_OUT    |CCR_4      |CCR_3       |CCR_2       |CCR_1       |ACC         |
|---------|------------|------------|------------|------------|-----------|------------|------------|------------|------------|
|cifar10  |79.95 ± 0.56|79.38 ± 0.04|80.09 ± 0.21|76.69 ± 0.14|0.99 ± 0.45|5.94 ± 1.74 |19.38 ± 0.28|49.84 ± 0.32|77.25 ± 0.09|
|tin      |74.18 ± 1.69|83.25 ± 0.13|88.47 ± 0.06|73.31 ± 0.74|1.93 ± 0.93|7.72 ± 1.27 |27.39 ± 0.33|56.53 ± 0.11|77.25 ± 0.09|
|nearood  |77.06 ± 0.82|81.31 ± 0.08|84.28 ± 0.09|75.00 ± 0.31|1.46 ± 0.42|6.83 ± 0.42 |23.39 ± 0.11|53.19 ± 0.15|77.25 ± 0.09|
|mnist    |88.13 ± 0.90|78.29 ± 2.05|52.26 ± 5.62|94.86 ± 0.37|4.47 ± 1.05|13.12 ± 3.58|28.11 ± 5.07|52.24 ± 3.96|77.25 ± 0.09|
|svhn     |76.97 ± 2.63|81.41 ± 1.50|68.64 ± 2.04|90.36 ± 0.84|5.10 ± 0.75|11.49 ± 1.36|24.77 ± 1.62|53.12 ± 2.30|77.25 ± 0.09|
|texture  |80.74 ± 1.81|78.74 ± 0.81|86.25 ± 0.61|64.52 ± 1.34|1.04 ± 0.66|3.26 ± 1.49 |17.24 ± 1.28|49.20 ± 1.13|77.25 ± 0.09|
|places365|79.14 ± 0.85|80.28 ± 0.27|62.10 ± 0.56|91.90 ± 0.15|1.24 ± 0.28|5.24 ± 0.35 |22.72 ± 0.84|51.99 ± 0.66|77.25 ± 0.09|
|farood   |81.25 ± 0.60|79.68 ± 0.75|67.31 ± 1.43|85.41 ± 0.41|2.96 ± 0.30|8.28 ± 0.34 |23.21 ± 0.95|51.64 ± 1.20|77.25 ± 0.09|

## ImageNet-200
||FPR@95      |AUROC       |AUPR_IN     |AUPR_OUT    |CCR_4       |CCR_3       |CCR_2       |CCR_1       |ACC         |
|-----------|------------|------------|------------|------------|------------|------------|------------|------------|------------|
|ssb_hard   |72.84 ± 0.68|80.77 ± 0.01|46.25 ± 0.18|94.95 ± 0.02|0.11 ± 0.11 |1.51 ± 0.16 |10.49 ± 0.29|50.09 ± 0.16|86.37 ± 0.08|
|ninco      |64.50 ± 1.30|86.64 ± 0.04|91.43 ± 0.06|77.48 ± 0.07|2.70 ± 0.38 |8.23 ± 1.64 |30.30 ± 0.50|65.63 ± 0.39|86.37 ± 0.08|
|nearood    |68.67 ± 0.99|83.71 ± 0.02|68.84 ± 0.08|86.22 ± 0.05|1.41 ± 0.23 |4.87 ± 0.78 |20.40 ± 0.16|57.86 ± 0.23|86.37 ± 0.08|
|inaturalist|39.10 ± 0.72|93.77 ± 0.27|94.42 ± 0.23|93.02 ± 0.33|13.97 ± 2.79|36.59 ± 3.55|59.69 ± 0.92|78.47 ± 0.64|86.37 ± 0.08|
|textures   |43.89 ± 0.83|90.16 ± 0.13|93.37 ± 0.14|84.83 ± 0.01|0.78 ± 0.81 |4.56 ± 0.76 |20.17 ± 1.10|70.06 ± 0.76|86.37 ± 0.08|
|openimage_o|55.68 ± 0.87|90.14 ± 0.08|87.41 ± 0.04|92.63 ± 0.13|3.93 ± 1.94 |14.86 ± 1.62|44.89 ± 1.02|73.14 ± 0.29|86.37 ± 0.08|
|farood     |46.22 ± 0.52|91.36 ± 0.10|91.73 ± 0.08|90.16 ± 0.15|6.23 ± 0.70 |18.67 ± 1.72|41.58 ± 0.63|73.89 ± 0.44|86.37 ± 0.08|

## ImageNet-200 (full-spectrum)
||FPR@95      |AUROC       |AUPR_IN     |AUPR_OUT    |CCR_4      |CCR_3       |CCR_2       |CCR_1       |ACC         |
|-----------|------------|------------|------------|------------|-----------|------------|------------|------------|------------|
|ssb_hard   |97.33 ± 0.18|48.36 ± 0.25|50.37 ± 0.07|49.83 ± 0.24|0.04 ± 0.03|0.45 ± 0.04 |3.03 ± 0.11 |16.73 ± 0.08|43.92 ± 0.12|
|ninco      |96.39 ± 0.41|54.92 ± 0.35|91.37 ± 0.07|12.40 ± 0.15|0.79 ± 0.11|2.38 ± 0.48 |9.34 ± 0.19 |24.01 ± 0.30|43.92 ± 0.12|
|nearood    |96.86 ± 0.28|51.64 ± 0.30|70.87 ± 0.07|31.11 ± 0.20|0.41 ± 0.07|1.42 ± 0.23 |6.19 ± 0.08 |20.37 ± 0.19|43.92 ± 0.12|
|inaturalist|88.63 ± 1.15|69.37 ± 0.86|91.55 ± 0.26|30.68 ± 1.04|4.10 ± 0.87|11.52 ± 1.22|21.05 ± 0.47|32.38 ± 0.49|43.92 ± 0.12|
|textures   |84.24 ± 0.67|66.24 ± 0.43|94.07 ± 0.10|20.17 ± 0.35|0.24 ± 0.24|1.31 ± 0.21 |6.01 ± 0.33 |26.50 ± 0.37|43.92 ± 0.12|
|openimage_o|92.90 ± 0.37|60.89 ± 0.29|83.50 ± 0.10|32.81 ± 0.34|1.12 ± 0.54|4.37 ± 0.48 |14.62 ± 0.36|28.37 ± 0.17|43.92 ± 0.12|
|farood     |88.59 ± 0.73|65.50 ± 0.46|89.71 ± 0.13|27.89 ± 0.54|1.82 ± 0.23|5.73 ± 0.56 |13.89 ± 0.21|29.08 ± 0.29|43.92 ± 0.12|

### ResNet50
||FPR@95      |AUROC       |AUPR_IN     |AUPR_OUT    |CCR_4      |CCR_3       |CCR_2       |CCR_1       |ACC         |
|-----------|------------|------------|------------|------------|-----------|------------|------------|------------|------------|
|ssb_hard   |86.22       |72.20       |71.51       |70.03       |0.21       |1.70        |8.74        |34.46       |76.19       |
|ninco      |76.59       |81.91       |97.15       |31.95       |2.83       |7.99        |23.36       |52.16       |76.19       |
|nearood    |81.41       |77.06       |84.33       |50.99       |1.52       |4.84        |16.05       |43.31       |76.19       |
|inaturalist|45.79       |92.45       |98.23       |71.13       |7.46       |17.93       |47.56       |68.30       |76.19       |
|textures   |57.71       |87.50       |98.11       |45.13       |0.10       |0.71        |16.18       |59.69       |76.19       |
|openimage_o|60.87       |89.25       |96.11       |69.72       |4.45       |14.12       |39.30       |64.25       |76.19       |
|farood     |54.79       |89.73       |97.48       |61.99       |4.00       |10.92       |34.35       |64.08       |76.19       |

### ViT-B/16
||FPR@95      |AUROC       |AUPR_IN     |AUPR_OUT    |CCR_4      |CCR_3       |CCR_2       |CCR_1       |ACC         |
|-----------|------------|------------|------------|------------|-----------|------------|------------|------------|------------|
|ssb_hard   |86.41       |68.53       |64.79       |68.10       |0.10       |0.56        |3.32        |25.41       |81.14       |
|ninco      |72.46       |80.60       |96.23       |34.65       |0.09       |0.35        |3.33        |45.15       |81.14       |
|nearood    |79.43       |74.57       |80.51       |51.37       |0.09       |0.45        |3.32        |35.28       |81.14       |
|inaturalist|39.85       |92.94       |98.18       |72.97       |0.08       |2.59        |40.76       |73.29       |81.14       |
|textures   |47.48       |89.93       |98.50       |53.76       |0.42       |1.62        |22.32       |66.46       |81.14       |
|openimage_o|52.42       |89.42       |95.31       |72.77       |0.17       |0.81        |16.28       |66.82       |81.14       |
|farood     |46.58       |90.77       |97.33       |66.50       |0.22       |1.67        |26.45       |68.86       |81.14       |

### Swin-T
||FPR@95      |AUROC       |AUPR_IN     |AUPR_OUT    |CCR_4      |CCR_3       |CCR_2       |CCR_1       |ACC         |
|-----------|------------|------------|------------|------------|-----------|------------|------------|------------|------------|
|ssb_hard   |84.51       |71.99       |68.67       |70.87       |0.09       |0.70        |4.58        |30.88       |81.59       |
|ninco      |68.63       |84.51       |97.36       |38.26       |0.39       |1.14        |12.92       |57.53       |81.59       |
|nearood    |76.57       |78.25       |83.02       |54.56       |0.24       |0.92        |8.75        |44.20       |81.59       |
|inaturalist|35.75       |93.88       |98.48       |74.96       |0.17       |5.42        |46.65       |74.90       |81.59       |
|textures   |52.83       |87.85       |98.07       |49.18       |0.18       |0.99        |12.40       |61.91       |81.59       |
|openimage_o|52.37       |89.95       |95.75       |73.10       |0.09       |1.14        |19.85       |68.26       |81.59       |
|farood     |46.98       |90.56       |97.44       |65.75       |0.15       |2.52        |26.30       |68.36       |81.59       |

### ResNet50
||FPR@95      |AUROC       |AUPR_IN     |AUPR_OUT    |CCR_4      |CCR_3       |CCR_2       |CCR_1       |ACC         |
|-----------|------------|------------|------------|------------|-----------|------------|------------|------------|------------|
|ssb_hard   |97.52       |53.18       |72.85       |33.25       |0.11       |0.94        |4.98        |20.53       |54.35       |
|ninco      |96.53       |63.02       |96.90       |7.20        |1.57       |4.53        |13.67       |32.38       |54.35       |
|nearood    |97.03       |58.10       |84.87       |20.22       |0.84       |2.74        |9.33        |26.45       |54.35       |
|inaturalist|82.80       |78.58       |97.35       |24.82       |4.23       |10.38       |29.17       |45.07       |54.35       |
|textures   |88.93       |71.76       |97.90       |9.55        |0.05       |0.39        |9.33        |37.92       |54.35       |
|openimage_o|91.39       |72.69       |94.70       |23.85       |2.49       |8.11        |23.70       |41.55       |54.35       |
|farood     |87.71       |74.35       |96.65       |19.40       |2.26       |6.29        |20.73       |41.51       |54.35       |

### ViT-B/16
||FPR@95      |AUROC       |AUPR_IN     |AUPR_OUT    |CCR_4      |CCR_3       |CCR_2       |CCR_1       |ACC         |
|-----------|------------|------------|------------|------------|-----------|------------|------------|------------|------------|
|ssb_hard   |97.92       |52.01       |70.14       |32.82       |0.06       |0.31        |2.04        |15.79       |61.49       |
|ninco      |95.75       |64.31       |96.66       |7.75        |0.05       |0.20        |2.04        |28.93       |61.49       |
|nearood    |96.83       |58.16       |83.40       |20.29       |0.05       |0.26        |2.04        |22.36       |61.49       |
|inaturalist|84.39       |80.23       |97.53       |23.83       |0.04       |1.60        |25.90       |50.87       |61.49       |
|textures   |86.09       |76.47       |98.32       |11.94       |0.24       |1.01        |13.82       |44.94       |61.49       |
|openimage_o|91.03       |74.96       |94.77       |25.99       |0.10       |0.46        |9.99        |45.25       |61.49       |
|farood     |87.17       |77.22       |96.87       |20.59       |0.12       |1.02        |16.57       |47.02       |61.49       |

### Swin-T
||FPR@95      |AUROC       |AUPR_IN     |AUPR_OUT    |CCR_4      |CCR_3       |CCR_2       |CCR_1       |ACC         |
|-----------|------------|------------|------------|------------|-----------|------------|------------|------------|------------|
|ssb_hard   |98.10       |52.98       |71.50       |32.99       |0.06       |0.41        |2.70        |18.23       |60.05       |
|ninco      |96.46       |65.86       |97.09       |7.83        |0.22       |0.68        |7.57        |35.74       |60.05       |
|nearood    |97.28       |59.42       |84.30       |20.41       |0.14       |0.54        |5.14        |26.99       |60.05       |
|inaturalist|86.20       |79.86       |97.53       |21.96       |0.10       |3.21        |28.37       |50.05       |60.05       |
|textures   |90.08       |71.89       |97.87       |9.62        |0.11       |0.59        |7.27        |39.00       |60.05       |
|openimage_o|92.61       |73.40       |94.58       |23.81       |0.06       |0.68        |11.63       |44.10       |60.05       |
|farood     |89.63       |75.05       |96.66       |18.47       |0.09       |1.49        |15.76       |44.38       |60.05       |

**Comment by zjysteven** [comment]
Thanks! I'll let you know in this thread once we integrate GEN into the leaderboard. I'm a little busy these days but should be able to finish in a week or so.

**Comment by zjysteven** [comment]
| | CIFAR-10 | CIFAR-100 | 
|:--------|:-------:|:-------:|
|reported| 88.20 ± 0.30 / 91.35 ± 0.69 | 81.31 ± 0.08 / 79.68 ± 0.75 |
|ours | 88.20 ± 0.30 / 91.35 ± 0.69 | 81.31 ± 0.08 / 79.68 ± 0.75 |

| | ImageNet-200 | ImageNet-200 (full-spectrum) |
|:--------|:-------:|:-------:|
|reported| 83.71 ± 0.02 / 91.36 ± 0.10 | 51.64 ± 0.30 / 65.50 ± 0.46 |
|ours | 83.68 ± 0.06 / 91.36 ± 0.10 | 51.59 ± 0.34 / 65.46 ± 0.44 |

| ResNet-50 | ImageNet-1K | ImageNet-1K (full-spectrum) |
|:--------|:-------:|:-------:|
|reported| 77.06 / 89.73  | 58.10 / 74.35 |
|ours | 76.85 / 89.76 | 57.84 / 74.31 |

| Swin-T | ImageNet-1K | ImageNet-1K (full-spectrum) |
|:--------|:-------:|:-------:|
|reported| 78.25 / 90.56 | 59.42 / 75.05 |
|ours | 78.97 / 90.98 | 60.36 / 76.00 |

| ViT-B-16 | ImageNet-1K | ImageNet-1K (full-spectrum) |
|:--------|:-------:|:-------:|
|reported| 74.57 / 90.77 | 58.16 / 77.22 |
|ours | 76.30 / 91.35 | 59.73 / 78.22 |

@coding-famer Hi, above are comparison between our evaluation and the reported results of GEN, in terms of near-OOD / far-OOD AUROC. There are slight differences in ImageNet results, which I guess might come from some dependency libraries(?). In a few cases the results on our end are even higher.

We have integrated GEN's results in our leaderboard. Closing this issue now, but feel free to reopen if you see any issues.
