### ISSUE TITLE
InD Accuracy

### ISSUE THREAD

**Issue by BierOne** [Jingkang50/OpenOOD#179]
Hi, there! 

Thank you for this outstanding work! I am a bit confused about the InD accuracy of the post hoc methods.
According to the original ASH and DICE papers, the methods modifying the network inevitability incur accuracy degradation. However, in Table 1, all post hoc methods preserve the InD accuracy since the propagation runs two times. 

I am wondering if it'd be beneficial to compare all methods using just one propagation. In my opinion, this can also serve as a way to effectively compare the existing post-hoc methods. Thanks.

**Comment by zjysteven** [comment]
My personal opinion on this is that, while the InD-OoD performance trade-off is interesting to study, in practice one can always use the original network/forward pass for InD classification without incurring significant extra computation. Many methods modify only the last few layers' behavior when computing OOD score, meaning that the forward pass within the majority early layers can be shared between InD classification and OoD detection.

That said, a single propagation is definitely more desired if the InD-OoD performance is of interest. The modification to the implementation should not be difficult.

**Comment by BierOne** [comment]
Got it :) Thank you!
