### ISSUE TITLE
Additional checkpoints on CIFAR benchmarks

### ISSUE THREAD

**Issue by BierOne** [Jingkang50/OpenOOD#180]
Hello Jingyang,

I hope you're doing well. I was wondering if it is possible to release additional checkpoints (e.g., CIDER, NPOS, CSI, AugMix, and PixMix) for CIFAR-10 and CIFAR-100 benchmarks. It would be very helpful. Thank you!

**Comment by zjysteven** [comment]
I can see if I still have these checkpoints available. I'm busy with something else, but will try to get back to you asap.

**Comment by zjysteven** [comment]
@BierOne I've uploaded the CIFAR-10/100 checkpoints for CIDER, NPOS, CSI, AugMix, and PixMix [here](https://drive.google.com/file/d/1f69wMWC5D5-jvr6HW5UUcibHqo50eHl0/view?usp=sharing).

**Comment by BierOne** [comment]
Thanks!
