### ISSUE TITLE
download.sh error

### ISSUE THREAD

**Issue by Lyttonkeepfoing** [Jingkang50/OpenOOD#185]
`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1XKzBdWCqg3vPoj-D32YixJyJJ0hL63gP (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb7f64621f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))`

I met this error when I want to download the OOD datasets. But I can still use google drive on the web. What's this problem? Or could you please update one google drive link to download these datasets directly?
It's a good repo!  And we want to do some fair comparison in our work with OpenOOD. So It's important to us!
Hope to get your respond soon!
    Best,

**Comment by zjysteven** [comment]
Hi @Lyttonkeepfoing thank you for your interest. It seems to me that the error is more on the gdrive side. And yes it could happen sometimes that on the web it works but the api won't.

I have two suggestions:
1. Make sure you install the latest version of gdrive.
2. You can make a copy of the datasets to your own google drive, which essentially will give you a new link that you can use to download. I would imagine that this can bypass that "Max retries exceeded" constraint.

**Comment by zjysteven** [comment]
Hi @Lyttonkeepfoing thank you for your interest in our work. The link/id `1XKzBdWCqg3vPoj-D32YixJyJJ0hL63gP` still works on my side though:
![image](https://github.com/Jingkang50/OpenOOD/assets/19763611/099ec48a-569b-460d-a57a-ee841e281d0a)
and from the error message it seems that something is blocking the connection and there is a networking issue.

**Comment by Lyttonkeepfoing** [comment]
Thannk you~

**Comment by zjysteven** [comment]
Closing for now. Feel free to reopen if there are any remaining issues.
