### ISSUE TITLE
Model selection

### ISSUE THREAD

**Issue by ivan-chai** [Jingkang50/OpenOOD#190]
Hi!

It's not clear from the paper whether the best or last training checkpoint is used for testing. What is the default choice for both small datasets and ImageNet?

**Comment by zjysteven** [comment]
For most training it was selected according to the validation ID accuracy.
https://github.com/Jingkang50/OpenOOD/blob/989c41dd3e3ebe85e6f5a5702acb6ce555715735/openood/recorders/base_recorder.py#L40

For certain methods the selection criterion could be different (e.g., OpenGAN explicitly needs to look at val OOD AUROC). You can refer to the code under https://github.com/Jingkang50/OpenOOD/tree/main/openood/recorders for details.
