### ISSUE TITLE
ImageNet-1k trianing datasets

### ISSUE THREAD

**Issue by 2454511550Lin** [Jingkang50/OpenOOD#191]
In a previous question, I know that we need to download the Imagenet-1K training set from official sources or other mirrors. Just to double-check, does OpenOOD rename images thus the name would be different from the official Imagenet1k? 

I kept getting the file cannot found error when selecting the training images in the script. (For example, in the imagenet1k KNN method.) It would be very helpful if you could point to me the mirror you were using (or the official source should work without any renaming?).

Thank you very much!

**Comment by zjysteven** [comment]
No we do not rename the images. You can check out `benchmark_imglist/imagenet/train_imagenet.txt` for details.
![image](https://github.com/Jingkang50/OpenOOD/assets/19763611/762f947d-6631-48fc-bd6e-4f72ae0c0cec)
My suggestion is to make sure the directory / path is correct.

**Comment by 2454511550Lin** [comment]
Thank you for the clarification. May I ask which version of imagenet are you using? According to the official website they have released the datasets from 2010 to 2017. Please see: https://image-net.org/download-images.php

I am using the 2010 version and I think some of the images are missing in the OpenOOD in those in benchmark_imglist/imagenet/train_imagenet.txt.

Thank you so much!

**Comment by zjysteven** [comment]
We are using the ILSVRC2012 version https://image-net.org/challenges/LSVRC/2012/2012-downloads.php, which I think is the most commonly used one.

**Comment by 2454511550Lin** [comment]
Thanks! I will try that.

**Comment by 2454511550Lin** [comment]
Just a quick follow-up, in the 2012 version training samples, apart from the 138GB main images file, there are "Training images (Task 3), 728MB". Is that also included in OpenOOD's pipeline? Thank you.

**Comment by zjysteven** [comment]
I was directly using the downloaded ImageNet on our lab server (which has been there for years) so I don't really know the exact corresponding files. My guess is that main file should be enough. I don't think there's anything special for preparing ILSVRC2012: I've been using many implementations from other people and the downloaded dataset is compatible with all of them without any modification.

**Comment by 2454511550Lin** [comment]
Sounds good, I will go for the main one and let you know. Thanks!
