### ISSUE TITLE
Unable to download dataset

### ISSUE THREAD

**Issue by yangengineering** [Jingkang50/OpenOOD#196]
I'm sorry, we can't download the google files because we don't have VPN on our server, can you provide the download link for the datasets? I also have a question about the train and test dataset of imagenet200, can you provide the link to download this dataset?

**Comment by yangengineering** [comment]
I guess I didn't phrase it clearly, I want to download the dataset locally, but I don't have a link to the dataset on google cloud, so I was wondering if you guys could provide the link, because as in question 197, I can't download the dataset using the code.

**Comment by zjysteven** [comment]
Yes if you take a look at `OpenOOD/scripts/download/download.py` you can see the encoded gdrive ID for each dataset, e.g.
https://github.com/Jingkang50/OpenOOD/blob/555d879be07d977f6ccf091b559afd64b37fc6f2/scripts/download/download.py#L93-L95
