### ISSUE TITLE
 the normalization of OOD test datasets

### ISSUE THREAD

**Issue by Esther-PAN** [Jingkang50/OpenOOD#198]
Hello, I have encountered an issue regarding the normalization of OOD test datasets. As per my understanding, during the evaluation of OOD datasets, it is necessary to perform normalization specific to each OOD test dataset. Taking CIFAR-100 as an example, where can I find the mean and standard deviation for the normalization of various OOD datasets? Thank you

**Comment by Esther-PAN** [comment]
for example， the mean and std for svhn\tin\texture\places365....

**Comment by zjysteven** [comment]
Actually one should NOT "perform normalization specific to each OOD test dataset". By doing so you are assuming that you know which dataset the input is from in the first place, which makes OOD detection meaningless (you already know whether the input is OOD or ID).

Therefore we just use the normalization parameters corresponding to each ID dataset, which we believe is reasonable and also practical. You can find the parameters here:
https://github.com/Jingkang50/OpenOOD/blob/555d879be07d977f6ccf091b559afd64b37fc6f2/openood/preprocessors/transform.py#L3-L12

**Comment by Esther-PAN** [comment]
Thank you for your prompt reply！
Can I understand it this way: if I use CIFAR-100 as the ID dataset, then when conducting out-of-distribution detection on various OOD datasets, all OOD datasets should be normalized using the same normalization parameters as CIFAR-100?

**Comment by Esther-PAN** [comment]
Or OOD test datasets do not need to be normalized to maintain the differences in their distributions?

**Comment by zjysteven** [comment]
> if I use CIFAR-100 as the ID dataset, then when conducting out-of-distribution detection on various OOD datasets, all OOD datasets should be normalized using the same normalization parameters as CIFAR-100

Correct. You can also imagine that in practice, a deployed image classifier typically uses a fixed set of preprocessing operations.

**Comment by Esther-PAN** [comment]
thanks sooo much！
