### ISSUE TITLE
tin597 class name

### ISSUE THREAD

**Issue by ma-kjh** [Jingkang50/OpenOOD#199]
Thank you for your benchmark dataset.

I just want to know the all of 597 classes name.

"Named as TIN-597, the resulting dataset has 597 classes which do not overlap with any of the categories from test OOD and serves as a good candidate for train OOD."

When I follow above description, I found 682 classes.

How can I get them ?

**Comment by zjysteven** [comment]
![image](https://github.com/Jingkang50/OpenOOD/assets/19763611/7cfcff27-9f4f-4992-8396-330293743a5f)
You can find the class names (wordnet IDs in ImageNet) if you download the `benchmark_imglist.zip` [here](https://drive.google.com/file/d/1XKzBdWCqg3vPoj-D32YixJyJJ0hL63gP/view?usp=drive_link) and go to `benchmark_imglist/cifar10/train_tin597.txt`.
