### ISSUE TITLE
Error occurs when unzipping the data.zip file on linux.

### ISSUE THREAD

**Issue by ZouXinn** [Jingkang50/OpenOOD#200]
After downloading the given data, I got a file named "data.zip". 

Then I uploaded it to my server and used the command **"unzip data.zip"**. However, errors occured as:

``` 
Archive:  data.zip
warning [data.zip]:  6299654520 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [data.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

I  search on the internet and the answers in [stackoverflow](https://stackoverflow.com/questions/56031185/unable-to-unzip-zip-file-on-linux-machine) suggest using the command **"7z x data.zip"**. After running it, I find that some files are extracted, however, many files are lost (all files in images_medical and images_largescale and part of the files in images_classic are lost).

Is there some solutions to this problem?
Thanks.

**Comment by zjysteven** [comment]
We don't really have a single file named `data.zip` in the v1.5 release. Which dataset were you trying to download?

**Comment by ZouXinn** [comment]
I tries to download the file "data" in the [data link](https://entuedu-my.sharepoint.com/personal/jingkang001_e_ntu_edu_sg/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fjingkang001%5Fe%5Fntu%5Fedu%5Fsg%2FDocuments%2Fopenood). I click the "download" button and then get a file named "data.zip".

**Comment by zjysteven** [comment]
Please follow [this part](https://github.com/Jingkang50/OpenOOD#data) in the README to download the data. The link you pointed to was for earlier v1.0 release.

BTW where did you get the "data link"? I thought we have removed it from the README.

**Comment by ZouXinn** [comment]
Thanks a lot. I get the data link in the "get started" part in the wiki. Here is the [link to that part](https://github.com/Jingkang50/OpenOOD/wiki/0.-Get-Started).

**Comment by ZouXinn** [comment]
It seems that I follow the "get started" part for version 1. Thank you a lot for your clarification.

**Comment by zjysteven** [comment]
No problem. We will clear things up a little bit to avoid confusion between v1.0 and v1.5. Thanks for your understanding.
