### ISSUE TITLE
It seens that  "torchvision=0.9.1" does not have VisionTransformer

### ISSUE THREAD

**Issue by ZouXinn** [Jingkang50/OpenOOD#201]
I create the conda environment according to the "environment.yml" file, and then run the command "sh scripts/basics/mnist/train_mnist.sh". However, an error "ModuleNotFoundError: No module named 'torchvision.models.vision_transformer'" occurs, which origins from the code "from torchvision.models.vision_transformer import VisionTransformer" in line 2 in vit_b_16.py.

I checked the codes in the file torchvision. models and found that there is no VisionTransformer. Then, I search in the official documents for torchvision and found that VisionTransformer is not implemented in the version v0.9.0. It seems that vision transformer first appears in the version v0.12 (I checked it version by version).

So I wonder that is there some issues in the "environment.yml" file ?

**Comment by zjysteven** [comment]
Again, please follow the [README](https://github.com/Jingkang50/OpenOOD#installation) for dependencies. `environment.yml` was a legacy file in v1.0 (and we should have removed it in v1.5), sorry for the confusion. Meanwhile I believe the README is very helpful for these setup questions where we have provided the up-to-date instructions.
