### ISSUE TITLE
The Difference between fsood and ood evaluator?

### ISSUE THREAD

**Issue by HengGao12** [Jingkang50/OpenOOD#205]
Hello, I would like to ask what's the difference between fsood and ood evaluator?

**Comment by zjysteven** [comment]
They evaluate performance under full-spectrum detection (fsood) and standard detection (ood) setting, respectively. Please refer Figure 3 of our [report](https://arxiv.org/pdf/2306.09301.pdf) for details.
![image](https://github.com/Jingkang50/OpenOOD/assets/19763611/d1a0516d-b746-44d3-b824-5be5b1f03134)

**Comment by HengGao12** [comment]
> They evaluate performance under full-spectrum detection (fsood) and standard detection (ood) setting, respectively. Please refer Figure 3 of our [report](https://arxiv.org/pdf/2306.09301.pdf) for details. ![image](https://user-images.githubusercontent.com/19763611/284343683-d1a0516d-b746-44d3-b824-5be5b1f03134.png)

Thank you for your reply, it really helps me a lot!
