### ISSUE TITLE
Does the dataset have to be placed in ./data/images_largescale?

### ISSUE THREAD

**Issue by WenhaiWan** [Jingkang50/OpenOOD#209]
Hi! I have a question. Does the dataset have to be placed in ./data/images_largescale?

**Comment by zjysteven** [comment]
Yes, our pipeline assumes that datasets are placed under either `./data/images_largescale` or `./data/images_classic`. You can look at the config for each dataset to see specifically its supposed location (e.g., the `data_dir` field in `configs/datasets/imagenet.yml` specifies that its location should be `./data/images_largescale/`).

**Comment by zjysteven** [comment]
I think that customization is achievable if you just change the location specified in the config file to your desired one.

**Comment by WenhaiWan** [comment]
Another question is, when I run ./scripts/basics/cifar100/train_cifar100.sh, it raises an error saying 'srun not found.' This may be related to the installation of Slurm, but I am currently only training on my local machine. Is it possible to avoid using srun-related commands?

**Comment by zjysteven** [comment]
It can be downloaded from google drive. You can either use our [download script](https://github.com/Jingkang50/OpenOOD/blob/main/scripts/download/download.py) or download it yourself with the gdrive id `1XKzBdWCqg3vPoj-D32YixJyJJ0hL63gP` (it is encoded in the download script too). This is also instructed in our [README](https://github.com/Jingkang50/OpenOOD#data).

**Comment by WenhaiWan** [comment]
Thank you so much for your response and helpful solution!
