### ISSUE TITLE
Slack invitation link?

### ISSUE THREAD

**Issue by matchyc** [Jingkang50/OpenOOD#214]
The current Slack link seems to redirect to sign-in, not an invitation link. So I can't join the Slack workspace.

**Comment by zjysteven** [comment]
@Jingkang50 Just to make sure, do we have any special considerations for inviting community people to our slack channel?

**Comment by zjysteven** [comment]
@matchyc Can you try this one https://join.slack.com/t/openood/shared_invite/zt-28xpcgf7b-MKomCMyrxto17M3NnOjYHA

**Comment by Jingkang50** [comment]
To be honest, I do not have any special considerations yet, just invite and see what will happen there lol. I can imagine at least there could be some very quick QA. 🍺
