### ISSUE TITLE
Submit results to the leaderboard.

### ISSUE THREAD

**Issue by kai422** [Jingkang50/OpenOOD#219]
Hi,

Great benchmark! I wonder if I could submit my results to the leaderboard?

Regards,
Kai

**Comment by zjysteven** [comment]
Yes of course! You can update your results in this thread and we will add them to the leaderboard. Meanwhile, if you want you can also contribute your method to OpenOOD by opening a pull request.

**Comment by kai422** [comment]
Thanks! I will submit a pull request shortly. By the way, this is a conflict between the environment.yml and setup.py, which is confusing for the installation.

**Comment by kai422** [comment]
Hi Jingyang,

I have uploaded the results file to [SCALE](https://github.com/kai422/SCALE/tree/main/results); you can view the results in this folder. The pretrained model for ISH is available on [Google Drive](https://drive.google.com/file/d/1EQimcdbJsKdU2uw4-BrqZO6tu4kXKtbG). Additionally, I have created a pull request for our postprocessor, SCALE, and will be uploading our training code shortly.

Regards,
Kai

**Comment by zjysteven** [comment]
Sure. We will update to the leaderboard asap. And for the environment setup, yeah it's a bit confusing. Please just use setup.py for pip install. We will remove environment.yml later.

**Comment by zjysteven** [comment]
@kai422 Congratulations to your ICLR paper and hitting a new SOTA on ImageNet leaderboard with SCALE and ISH! We have updated the leaderboard to include the results. For the pull request, let us know when the training code is ready just so we can merge once for both SCALE and ISH.
