### ISSUE TITLE
Can't find the file of SEM

### ISSUE THREAD

**Issue by keao23** [Jingkang50/OpenOOD#222]
Hi! I have a question. Which postprocessor file corresponds to the implementation of the method SEM?

**Comment by Jingkang50** [comment]
Please check [here](https://github.com/Jingkang50/OpenOOD/tree/main/scripts/ood/sem)

**Comment by keao23** [comment]
Thank you for your reply!

**Comment by jS5t3r** [comment]
Why the imagenet file loads `configs/postprocessors/gmm.yml`. Here: https://github.com/Jingkang50/OpenOOD/blame/18c6f5174a2f518e2a8e819ffb1cd1914bcf12e0/scripts/ood/sem/imagenet_test_ood_sem.sh#L19

This does not work: 

```bash
python scripts/eval_adversarial_ood_imagenet.py \
    --tvs-pretrained \
    --arch vit-b-16 \
    --postprocessor sem \ # or should be ensemble here?
    --save-score --save-csv
```

[There](https://github.com/Jingkang50/OpenOOD/blob/main/openood/evaluation_api/postprocessor.py) is no  `sem` available. Is `sem` and `ensemble` the same?

**Comment by zjysteven** [comment]
> Please check [here](https://github.com/Jingkang50/OpenOOD/tree/main/scripts/ood/sem)

As Jingkang mentioned, the script for `sem` can be found via that link, where you would see that currently `sem` is not supported with the newer evaluation api (which is called by `eval_ood_imagenet.py` in your comment).
