### ISSUE TITLE
add SAL (Separate And Learn) method

### ISSUE THREAD

**Issue by tfriedel** [Jingkang50/OpenOOD#226]
There's this new paper:
 [How Does Unlabeled Data Provably Help Out-of-Distribution Detection?](https://openreview.net/forum?id=jlEjB8MVGa) by Xuefeng Du, Zhen Fang, Ilias Diakonikolas, and Yixuan Li 
Performance is quite good according to their paper and they have published their source here
https://github.com/deeplearning-wisc/sal
Would be interesting how it compares to other methods.

**Comment by zjysteven** [comment]
Seems a promising work. Would you be interested to adapt it to OpenOOD?

**Comment by tfriedel** [comment]
Unfortunately I'm currently too busy, maybe in a few months.
