### ISSUE TITLE
Plans for supporting OoD Object Detection?

### ISSUE THREAD

**Issue by 1ho0jin1** [Jingkang50/OpenOOD#229]
Hi, thanks for your great work!
I saw in your paper that you plan to support OoD on object detection.
Do you have any specific timeline for this?

**Comment by zjysteven** [comment]
Unfortunately no, as the team has been working on something else. That said, seems that integrating OpenOOD into object detection application should be fairly straightforward, like one can directly apply some post-hoc methods to the classification head?
