### ISSUE TITLE
NAC results for OpenOOD Leadboard

### ISSUE THREAD

**Issue by BierOne** [Jingkang50/OpenOOD#232]
Hi, there! 

Nice benchmark! I'd like to submit my NAC results to the OpenOOD leadboard. I provided the results in this [link](https://drive.google.com/drive/folders/1xSVb_-kEndHg7ovx4hqpGCg-NwnJZ2nN?usp=sharing).

Additionally, here's the link to my paper (https://openreview.net/forum?id=SNGXbZtK6Q), and the GitHub repository (https://github.com/BierOne/ood_coverage).

Since my current implementation is based on an older version of OpenOOD,  I may take more time to open a pull request. Thank you!

**Comment by zjysteven** [comment]
Thanks for submitting the results! We will try to update the leaderboard asap.

**Comment by zjysteven** [comment]
Hi @BierOne, sorry that it's been taking a while, but we have included NAC results into the leaderboard. Please have a look and let us know if there are any issues.
