### ISSUE TITLE
T2FNorm results for OpenOOD Leaderboard

### ISSUE THREAD

**Issue by sudarshanregmi** [Jingkang50/OpenOOD#240]
The checkpoints for T2FNorm:

[CIFAR10](https://drive.google.com/file/d/1FchVmaDodfsSE-eyA6FjnEZ7FtFm0v4u/view?usp=drive_link)
[CIFAR100](https://drive.google.com/file/d/16bEDcPPjPkt4KmnqurfGnI6gPLIwZJc8/view?usp=drive_link)
[ImageNet200](https://drive.google.com/file/d/1i6Rsb11yr0cP6grjtyQI23sYfSH3fBBH/view?usp=drive_link)
[ImageNet-1k](https://drive.google.com/file/d/1vEfGSg0sIONLYu2XXxWixRAtE5YYVeUw/view?usp=sharing)

Results:

[cifar10_t2fnorm.csv](https://github.com/user-attachments/files/15594479/cifar10_t2fnorm.csv)
[cifar100_t2fnorm.csv](https://github.com/user-attachments/files/15594480/cifar100_t2fnorm.csv)
[imagenet200_ood_t2fnorm.csv](https://github.com/user-attachments/files/15594484/imagenet200_ood_t2fnorm.csv)
[imagenet200_fsood_t2fnorm.csv](https://github.com/user-attachments/files/15594483/imagenet200_fsood_t2fnorm.csv)
[imagenet_ood_t2fnorm.csv](https://github.com/user-attachments/files/15594482/imagenet_ood_t2fnorm.csv)
[imagenet_fsood_t2fnorm.csv](https://github.com/user-attachments/files/15594481/imagenet_fsood_t2fnorm.csv)

- **`Training`**: `T2FNorm`.
- **`Postprocessor`**: `t2fnorm`
- **`Outlier Data`**: No.

**Comment by zjysteven** [comment]
Included!
