### ISSUE TITLE
Error with the dowload.py script 

### ISSUE THREAD

**Issue by ZafeirisKanakis** [Jingkang50/OpenOOD#243]
Hello,
I have set up an enviroment so I can run the OpenOOD library and test it.
But when I am going to get the datasets and the models by runing the command like this:
python ./scripts\download\download.py --contents datasets checkpoints --datasets ood_v1.5 --checkpoints ood_v1.5  --save_dir ./data ./results --dataset_mode benchmark

I am geting this type of error 

Downloading...
From (original): https://drive.google.com/uc?id=1XKzBdWCqg3vPoj-D32YixJyJJ0hL63gP
From (redirected): https://drive.google.com/uc?id=1XKzBdWCqg3vPoj-D32YixJyJJ0hL63gP&confirm=t&uuid=22e1658b-8c0c-47d8-aac5-2dcaf160e611
To: C:\zafeiris\Σχολη\Πτυχιακη\code_papers\OpenOOD\data
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 27.7M/27.7M [00:02<00:00, 10.8MB/s]
Traceback (most recent call last):
  File "C:\zafeiris\Σχολη\Πτυχιακη\code_papers\OpenOOD\scripts\download\download.py", line 190, in <module>
    gdown.download(id=download_id_dict['benchmark_imglist'],
  File "C:\Users\zafei\.conda\envs\openood-env\lib\site-packages\gdown\download.py", line 381, in download
    shutil.move(tmp_file, output)
  File "C:\Users\zafei\.conda\envs\openood-env\lib\shutil.py", line 823, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path './data/x_km4fxk.part' already exists

Does anyone knows how to solve this problem?

Thanks a lot 
Zafeiris

**Comment by zjysteven** [comment]
The error message said it pretty much: shutil is moving something to a destination but there has already been a file. Try just manually remove your `./data/x_km4fxk.part` and run `download.py` again. Or a more brute-force (but maybe unnecessary) way is to delete your `./data` folder and rerun `download.py`.
