### ISSUE TITLE
Add fDBD to leaderboard

### ISSUE THREAD

**Issue by litianliu** [Jingkang50/OpenOOD#247]
Please see below the evaluation results of fDBD. All evaluations are on the default checkpoints provided in the codebase.

- **`Training`**:  `CrossEntropy`.
- **`Postprocessor`**: `fDBD`.
- **`Outlier Data`**:  `None`.

[cifar100_fdbd.csv](https://github.com/user-attachments/files/16228458/cifar100_fdbd.csv)
[cifar10_fdbd.csv](https://github.com/user-attachments/files/16228460/cifar10_fdbd.csv)
[imagenet200_fsood_fdbd.csv](https://github.com/user-attachments/files/16228461/imagenet200_fsood_fdbd.csv)
[imagenet200_ood_fdbd.csv](https://github.com/user-attachments/files/16228462/imagenet200_ood_fdbd.csv)
[imagenet_ood_fdbd.csv](https://github.com/user-attachments/files/16228463/imagenet_ood_fdbd.csv)
[imagenet_fsood_fdbd.csv](https://github.com/user-attachments/files/16228464/imagenet_fsood_fdbd.csv)

Please let me know if additional information is needed from my end. Thanks!

**Comment by zjysteven** [comment]
All fDBD entries are included. You can check the leaderboard and let me know if there are any issues.

**Comment by litianliu** [comment]
Thank you for your prompt response. I have checked the leaderboard, and it looks great!
