### ISSUE TITLE
Model Uncertainty methods

### ISSUE THREAD

**Issue by RoundOffError** [Jingkang50/OpenOOD#262]
Hello,

Thanks for maintaining this great resource.  I've found it very helpful in my own research.

I noticed the Model Uncertainty methods (DeepEnsemble and MCDropout) don't appear in the leaderboard.  They also don't seem to be in the OpenOOD v1.5 paper.

Do you see this uncertainty quantification-type research as being distinct from OOD research?  I'm curious to get your thoughts on this and to know if you have plans to expand OpenOOD to include UQ type work like Bayesian Neural Networks?

It seems to me that these research communities have similar goals but are oddly separate from one another in the literature.

Thanks!

**Comment by zjysteven** [comment]
Hi thank you for your interest and kind words. One reason I remember for not including e.g. DeepEnsemble in v1.5 was the inference cost of it on datasets like ImageNet-1K. My personal view is that UQ research is more general than OOD detection (e.g., uncertainty on ID inputs are also studied in UQ research but not really touched/cared by OOD detection). At the moment we don't have plan to include UQ type works/methods, but as always we would welcome community contributions.

**Comment by RoundOffError** [comment]
Thanks for the quick response!
