### ISSUE TITLE
Request for Full Experimental Results of OpenOOD v1.5

### ISSUE THREAD

**Issue by 1409169341** [Jingkang50/OpenOOD#265]
I am currently working on a research paper and would like to use the experimental results of OpenOOD v1.5 in my experiments. However, I noticed that the full experimental results on all OOD datasets are not available on the GitHub page or in the leaderboard.

Would it be possible for you to provide the full experimental results of OpenOOD v1.5 on all the OOD datasets? These results are crucial for my research, and I would greatly appreciate it if you could share them or provide them in any accessible format.

**Comment by zjysteven** [comment]
https://docs.google.com/spreadsheets/d/1mTFrO-_STYBRcNMMEmHQrFPQzeg6S8Z2vRA8jawTwBw/edit?usp=sharing This google sheet should be helpful.

**Comment by 1409169341** [comment]
Thank you so much for your prompt response and for providing the full experimental results. I truly appreciate your help and support.
