### ISSUE TITLE
MOS OpenSet

### ISSUE THREAD

**Issue by hendrycks** [Jingkang50/OpenOOD#42]
In the README, why is MOS under Open Set since it has OOD in the title?

**Comment by Jingkang50** [comment]
Thank you Dan for your question. 
Yes, MOS should be better fit in OOD section as its title says. 
I put it under openset mainly according to [our survey](https://arxiv.org/pdf/2110.11334.pdf) section 4.1.4, where MOS first appears in the paper. 
The mentioned section means that MOS arranges the large semantic space into a hierarchical taxonomy of known classes and is able to address OSR problem (even though it only follows OOD setting).
But you are right, we should make the categorization more straightforward and return MOS to the OOD team.
