### ISSUE TITLE
use default settings to overwrite command line arguments 

### ISSUE THREAD

**Issue by jingzhengli** [Jingkang50/OpenOOD#72]
Hi, 
I want to use default settings to replace command line arguments like
_parser.add_argument('--config', dest='config', nargs='+', required=True, default = ['configs/datasets/digits/mnist.yml', 'configs/networks/lenet.yml','configs/pipelines/train/baseline.yml'])_  but an error occured. 
How to deal with such problems? Thank you very much~

**FileNotFoundError: [Errno 2] No such file or directory: 'configs/datasets/digits/mnist.yml configs/networks/lenet.yml configs/pipelines/train/baseline.yml**

**Comment by Jingkang50** [comment]
Thank you for the question.
Make sure you are running from the root of this repo. I felt like this error is about your env variables.
Hope it helps.

**Comment by jingzhengli** [comment]
> 

Thanks for your quick reply. The error was solved. Just a formatting error.
Nice code.

**Comment by Jingkang50** [comment]
Thanks!
